# Pytorch Fundamentals

Resource : https://www.learnpytorch.io/00_pytorch_fundamentals/

In [5]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.8.0+cu126


## Introduction to Tensors

### Creating Tensors

In [6]:
# Scalar

scalar = torch.tensor(7)
scalar

tensor(7)

In [8]:
scalar.ndim # no dimensions

0

In [9]:
# Get tensor back as python int
scalar.item()

7

In [10]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [11]:
vector.ndim

1

In [13]:
vector.shape

torch.Size([2])

In [14]:
# Matrix
matrix = torch.tensor([[7,1],[9,10]])
matrix

tensor([[ 7,  1],
        [ 9, 10]])

In [15]:
matrix.ndim

2

In [16]:
matrix[1]

tensor([ 9, 10])

In [19]:
matrix.shape

torch.Size([2, 2])

In [20]:
# TENSOR

TENSOR = torch.tensor([[[1,2,3],[2,3,4],[4,5,6]]])
TENSOR

tensor([[[1, 2, 3],
         [2, 3, 4],
         [4, 5, 6]]])

In [21]:
TENSOR.ndim

3

In [22]:
TENSOR.shape

torch.Size([1, 3, 3])

In [25]:
TENSOR[0]

tensor([[1, 2, 3],
        [2, 3, 4],
        [4, 5, 6]])

### Random Tensors

In [27]:
# Create random tensor
random_tensor = torch.rand(3,2,5)
random_tensor

tensor([[[0.0985, 0.4840, 0.1058, 0.6154, 0.9672],
         [0.5239, 0.7533, 0.6988, 0.6230, 0.5613]],

        [[0.1103, 0.3094, 0.3504, 0.3921, 0.6604],
         [0.2507, 0.0225, 0.4365, 0.8239, 0.1526]],

        [[0.1117, 0.1763, 0.7298, 0.0176, 0.2439],
         [0.4415, 0.3125, 0.8262, 0.2863, 0.2307]]])

In [31]:
image_tensor = torch.rand(size = (224,224,3))
image_tensor.shape, image_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeroes and Ones

In [34]:
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [39]:
ones = torch.ones(2,3,2)
ones

tensor([[[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]]])

In [36]:
ones.dtype

torch.float32

### Creating a range of Tensors

In [44]:
onetoten = torch.arange(0,10)
onetoten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
torch.arange(start = 0, end = 100, step = 10)

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [46]:
ten_zeros = torch.zeros_like(onetoten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Datatypes

3 big errors:
- Tensors not right datatype
- Tensors not right shape
- Tensors not on right device

Precision in computing

In [47]:
float_tensor = torch.tensor([3.0,6.0,9.0],
                            dtype=None,  # eg. float16, float32 (They show precision)
                            device=None,  # what device the tensor is on
                            requires_grad=True)  # Whether or not to track gradients with the tensor operations
float_tensor

tensor([3., 6., 9.], requires_grad=True)

In [48]:
float_tensor.dtype

torch.float32

In [49]:
float_16_tensor = float_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16, grad_fn=<ToCopyBackward0>)

In [53]:
int_32_tensor = torch.tensor([3,6,9], dtype = int)
int_32_tensor

tensor([3, 6, 9])

### Getting information abt tensor

In [54]:
some_tensor = torch.rand(3,4)

In [55]:
print(some_tensor)

tensor([[0.5404, 0.1428, 0.0221, 0.0143],
        [0.7697, 0.3478, 0.9746, 0.6002],
        [0.3238, 0.0261, 0.0209, 0.8501]])


In [56]:
some_tensor.size()

torch.Size([3, 4])

In [58]:
some_tensor.shape

torch.Size([3, 4])

In [59]:
some_tensor.device

device(type='cpu')

### Manipulating Tensors

In [61]:
tensor = torch.tensor([1,2,3])
tensor+10

tensor([11, 12, 13])

In [62]:
tensor*10

tensor([10, 20, 30])

In [64]:
tensor-10

tensor([-9, -8, -7])

In [65]:
torch.mul(tensor,10)

tensor([10, 20, 30])

#### Matrix Multiplication
- Element-wise multiplication
- matrix multiplication (dot product)

Possible errors:
- inner dimensions should match

In [67]:
print(tensor, "*", tensor)
print(tensor*tensor)


tensor([1, 2, 3]) * tensor([1, 2, 3])
tensor([1, 4, 9])


In [68]:
torch.matmul(tensor,tensor)

tensor(14)

In [70]:
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]], dtype=torch.float32).T # Using Transpose

torch.matmul(tensor_A, tensor_B)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [71]:
print(tensor_A)
print(tensor_A.T)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[1., 3., 5.],
        [2., 4., 6.]])


### Finding min,max,sum etc

In [84]:
x = torch.arange(1,100,10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [85]:
torch.max(x), x.max()

(tensor(91), tensor(91))

In [86]:
#torch.mean() will show us an error

torch.mean(x.type(torch.float32)), x.type(torch.float16).mean()

(tensor(46.), tensor(46., dtype=torch.float16))

In [87]:
torch.sum(x)

tensor(460)

### Finding the positional min and max

In [88]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [89]:
x.argmax()

tensor(9)

In [90]:
x[9]

tensor(91)

### Reshaping, Stacking, Squeezing and Unsqueezing


In [91]:
x = torch.arange(1.,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [95]:
# Reshaping
x_reshaped = x.reshape(9,1)
x_reshaped

tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [113]:
x_reshaped = x.reshape(1,9)
x_reshaped

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [111]:
x_rreshaped = x.reshape(3,3)
x_rreshaped

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [102]:
# View
z = x.view(1,9)
z

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [130]:
# Stacking
x_stacked = torch.stack([x,x,x,x],dim = 0)
print(x_stacked)
x_stacked = torch.stack([x,x,x,x],dim = 1)
x_stacked

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.]])


tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [121]:
# Squeezing
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [124]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [127]:
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

## Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [134]:
x_original = torch.rand(size=(223,224,3))
# permute rearranges the dimensions of the target tensor in the specified order
x_permuted = x_original.permute(2,0,1)
print(x_original.shape)
print(x_permuted.shape)

torch.Size([223, 224, 3])
torch.Size([3, 223, 224])


### Indexing

In [142]:
x = torch.arange(1,19).reshape(2,3,3)
x, x.shape

(tensor([[[ 1,  2,  3],
          [ 4,  5,  6],
          [ 7,  8,  9]],
 
         [[10, 11, 12],
          [13, 14, 15],
          [16, 17, 18]]]),
 torch.Size([2, 3, 3]))

In [143]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [146]:
x[1][0]

tensor([10, 11, 12])

In [145]:
x[0][0][1]

tensor(2)

In [147]:
x[:,0]

tensor([[ 1,  2,  3],
        [10, 11, 12]])

In [148]:
x[:,:,0]

tensor([[ 1,  4,  7],
        [10, 13, 16]])

In [149]:
x[:,1,1]

tensor([ 5, 14])

## Numpy and Pytorch

In [152]:
array = np.arange(1.0,9.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8.], dtype=torch.float64))

In [153]:
array = array+1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8., 9.]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8.], dtype=torch.float64))

In [155]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility

to reduce the randomness in neural networks and pytorch comes the concept of **random seed**.

In [156]:
# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(f"Tensor A:\n{random_tensor_A}\n")
print(f"Tensor B:\n{random_tensor_B}\n")
print(f"Does Tensor A equal Tensor B? (anywhere)")
random_tensor_A == random_tensor_B

Tensor A:
tensor([[9.3503e-01, 4.1066e-01, 9.4177e-02, 9.2270e-01],
        [4.6310e-01, 9.8465e-01, 1.7915e-01, 3.7491e-01],
        [8.8662e-01, 3.4451e-04, 9.6035e-01, 5.0098e-02]])

Tensor B:
tensor([[0.0475, 0.7993, 0.0973, 0.4553],
        [0.8884, 0.0589, 0.2363, 0.7279],
        [0.6759, 0.7817, 0.5194, 0.0345]])

Does Tensor A equal Tensor B? (anywhere)


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [159]:
RANDOM_SEED = 42

torch.manual_seed(seed=RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

# Have to reset the seed every time a new rand() is called
# Without this, tensor_D would be different to tensor_C
torch.random.manual_seed(seed=RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(f"Tensor C:\n{random_tensor_C}\n")
print(f"Tensor D:\n{random_tensor_D}\n")
print(f"Does Tensor C equal Tensor D? (anywhere)")
random_tensor_C == random_tensor_D

Tensor C:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Tensor D:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Does Tensor C equal Tensor D? (anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

## Running tensors and Pytorch objects on GPU

In [161]:
!nvidia-smi

Thu Aug 28 15:39:04 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   39C    P8              9W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [162]:
# check for GPU access with Pytorch

torch.cuda.is_available()

True

In [163]:
# setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [164]:
torch.cuda.device_count()

1

### Putting tensors on the GPU

In [166]:
tensor = torch.tensor([1,2,3],device = "cpu")
tensor.device

device(type='cpu')

In [167]:
# move tensor to gpu if available
tensor_to_gpu = tensor.to(device)
tensor_to_gpu

tensor([1, 2, 3], device='cuda:0')

In [171]:
# Moving back to CPU
#tensor_to_gpu.numpy()

# TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [170]:
tensor_back_on_cpu = tensor_to_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])