# Importing pytorch

In [2]:
import torch

# Creating tensors

In [4]:
# Everything in pytorch is based on Tensor operations.
# A tensor can have different dimensions
# so it can be 1d, 2d, or even 3d and higher

# scalar, vector, matrix, tensor

# torch.empty(size): uninitiallized
x = torch.empty(1) # scalar
print(x)
x = torch.empty(3) # vector, 1D
print(x)
x = torch.empty(2,3) # matrix, 2D
print(x)
x = torch.empty(2,2,3) # tensor, 3 dimensions
print(x)
x = torch.empty(2,2,2,3) # tensor, 4 dimensions
print(x)

tensor([0.])
tensor([0., 0., 0.])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])
tensor([[[[0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.]]],


        [[[0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.]]]])


In [5]:
x = torch.rand(5, 3)
print(x)

# torch.zeros(size), fill with 0
# torch.ones(size), fill with 1
x = torch.zeros(5, 3)
print(x)

# check size
print(x.size())

# check data type
print(x.dtype)

tensor([[0.3580, 0.0575, 0.3952],
        [0.6962, 0.8561, 0.2048],
        [0.2568, 0.1841, 0.6279],
        [0.5035, 0.3229, 0.1128],
        [0.4278, 0.4837, 0.3766]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
torch.Size([5, 3])
torch.float32


In [7]:
x = torch.zeros(5, 3, dtype=torch.int)
print(x)

# check type
print(x.dtype)

# construct from data
x = torch.tensor([5.5, 3])
print(x.size())

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)
torch.int32
torch.Size([2])


# Requires_grad argument

In [9]:
# requires_grad argument
# This will tell pytorch that it will need to calculate the gradients for this tensor
# later in your optimization steps
# i.e. this is a variable in your model that you want to optimize
x = torch.tensor([5.5, 3], requires_grad=True)
print(x)

tensor([5.5000, 3.0000], requires_grad=True)


# Adding Tensors

In [10]:
# Operations
y = torch.rand(2, 2)
x = torch.rand(2, 2)

# elementwise addition
z = x + y
# torch.add(x,y)

# in place addition, everythin with a trailing underscore is an inplace operation
# i.e. it will modify the variable
# y.add_(x)

print(x)
print(y)
print(z)

tensor([[0.4927, 0.3556],
        [0.8432, 0.5746]])
tensor([[0.7797, 0.2379],
        [0.4832, 0.5643]])
tensor([[1.2724, 0.5935],
        [1.3263, 1.1389]])


# Other operations

In [11]:
z = x - y
z = torch.sub(x, y)
print(z)
# multiplication
z = x * y
z = torch.mul(x,y)
print(z)
# division
z = x / y
z = torch.div(x,y)
print(z)

tensor([[-0.2869,  0.1177],
        [ 0.3600,  0.0103]])
tensor([[0.3842, 0.0846],
        [0.4074, 0.3242]])
tensor([[0.6320, 1.4946],
        [1.7451, 1.0182]])


# Slicing

In [12]:
x = torch.rand(5,3)
print(x)
print(x[:, 0]) # all rows, column 0
print(x[1, :]) # row 1, all columns
print(x[1,1]) # element at 1, 1

# Get the actual value if only 1 element in your tensor
print(x[1,1].item())

tensor([[0.5540, 0.1149, 0.2371],
        [0.9629, 0.2543, 0.5221],
        [0.0397, 0.6364, 0.2390],
        [0.6361, 0.5220, 0.0187],
        [0.2042, 0.2478, 0.5225]])
tensor([0.5540, 0.9629, 0.0397, 0.6361, 0.2042])
tensor([0.9629, 0.2543, 0.5221])
tensor(0.2543)
0.25428181886672974


# Reshape with torch.view()

In [15]:
x = torch.randn(4, 4)
print(x)
y = x.view(16)
print(y)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
# if -1 it pytorch will automatically determine the necessary size
print(z)
print(x.size(), y.size(), z.size())

tensor([[ 1.5521, -0.9749, -1.2434,  2.9769],
        [-0.4082, -0.4609, -0.2764,  1.3262],
        [-1.0317,  0.0268, -0.2572,  0.1464],
        [-0.2374, -0.4253, -0.7945,  0.9043]])
tensor([ 1.5521, -0.9749, -1.2434,  2.9769, -0.4082, -0.4609, -0.2764,  1.3262,
        -1.0317,  0.0268, -0.2572,  0.1464, -0.2374, -0.4253, -0.7945,  0.9043])
tensor([[ 1.5521, -0.9749, -1.2434,  2.9769, -0.4082, -0.4609, -0.2764,  1.3262],
        [-1.0317,  0.0268, -0.2572,  0.1464, -0.2374, -0.4253, -0.7945,  0.9043]])
torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


# Using Numpy

In [ ]:
# Converting a Torch Tensor to a NumPy array and vice versa is very easy
a = torch.ones(5)
print(a)

# torch to numpy with .numpy()
b = a.numpy()
print(b)
print(type(b))

# Carful: If the Tensor is on the CPU (not the GPU),
# both objects will share the same memory location, so changing one
# will also change the other
a.add_(1)
print(a)
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [ ]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
print(a)
print(b)

# again be careful when modifying
a += 1
print(a)
print(b)


[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
